import type {
  AuditAction,
  AuditActionType,
  AuditModule,
} from '@/types';

export const AUDIT_PAGE_SIZE = 40;

export const AUDIT_ACTION_TYPES: AuditActionType[] = [
  'CREATE',
  'UPDATE',
  'DELETE',
  'ARCHIVE',
  'APPROVE',
  'REJECT',
  'DEACTIVATE',
  'RESTORE',
  'LOGIN',
  'LOGOUT',
  'READ',
  'CONFIGURATION_CHANGE',
  'SYSTEM',
];

export const AUDIT_MODULES: AuditModule[] = [
  'auth',
  'inventory',
  'waste',
  'expiry',
  'notifications',
  'cost',
  'analytics',
  'ai',
  'system',
  'staff',
];

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  batch_created: 'Batch created',
  batch_edited: 'Batch edited',
  batch_consumed: 'Batch consumed',
  batch_archived: 'Batch archived',
  threshold_updated: 'Expiry threshold updated',
  expiry_detected: 'Expiry detected',
  notification_sent: 'Notification sent',
  notification_failed: 'Notification failed',
  notification_delivered: 'Notification delivered',
  notification_opened: 'Notification opened',
  notification_read: 'Notification marked read',
  device_registered: 'Device registered',
  device_removed: 'Device removed',
  waste_created: 'Waste logged',
  waste_voided: 'Waste voided',
  inventory_restored: 'Inventory restored',
  staff_approved: 'Staff approved',
  staff_rejected: 'Staff rejected',
  staff_deactivated: 'Staff deactivated',
  user_login: 'User signed in',
  user_logout: 'User signed out',
  ai_settings_updated: 'AI settings updated',
  analytics_exported: 'Analytics exported',
  profile_updated: 'Profile updated',
  profile_photo_updated: 'Profile photo updated',
  restaurant_settings_updated: 'Restaurant settings updated',
  notification_prefs_updated: 'Notification preferences updated',
};

export const AUDIT_MODULE_LABELS: Record<AuditModule, string> = {
  auth: 'Authentication',
  inventory: 'Inventory',
  waste: 'Waste',
  expiry: 'Expiry',
  notifications: 'Notifications',
  cost: 'Cost',
  analytics: 'Analytics',
  ai: 'AI',
  system: 'System',
  staff: 'Staff',
};

export const CLIENT_AUDIT_ACTIONS: AuditAction[] = [
  'batch_created',
  'batch_edited',
  'batch_consumed',
  'batch_archived',
  'threshold_updated',
  'waste_created',
  'waste_voided',
  'inventory_restored',
  'device_registered',
  'device_removed',
  'notification_read',
  'notification_opened',
  'staff_approved',
  'staff_rejected',
  'staff_deactivated',
  'user_login',
  'user_logout',
  'analytics_exported',
  'profile_updated',
  'profile_photo_updated',
  'restaurant_settings_updated',
  'notification_prefs_updated',
];
