"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.voidWasteEntry = exports.createWasteLog = exports.cleanupInvalidFCMTokens = exports.evaluateInventoryExpiry = exports.deactivateStaff = exports.askAiAssistant = exports.generateContent = void 0;
const app_1 = require("firebase-admin/app");
const v2_1 = require("firebase-functions/v2");
(0, app_1.initializeApp)();
(0, v2_1.setGlobalOptions)({ maxInstances: 20 });
var generateContent_1 = require("./gemini/generateContent");
Object.defineProperty(exports, "generateContent", { enumerable: true, get: function () { return generateContent_1.generateContent; } });
var askAiAssistant_1 = require("./ai/askAiAssistant");
Object.defineProperty(exports, "askAiAssistant", { enumerable: true, get: function () { return askAiAssistant_1.askAiAssistant; } });
var deactivateStaff_1 = require("./auth/deactivateStaff");
Object.defineProperty(exports, "deactivateStaff", { enumerable: true, get: function () { return deactivateStaff_1.deactivateStaff; } });
var evaluateInventoryExpiry_1 = require("./expiry/evaluateInventoryExpiry");
Object.defineProperty(exports, "evaluateInventoryExpiry", { enumerable: true, get: function () { return evaluateInventoryExpiry_1.evaluateInventoryExpiry; } });
var cleanupInvalidFCMTokens_1 = require("./messaging/cleanupInvalidFCMTokens");
Object.defineProperty(exports, "cleanupInvalidFCMTokens", { enumerable: true, get: function () { return cleanupInvalidFCMTokens_1.cleanupInvalidFCMTokens; } });
var createWasteLog_1 = require("./waste/createWasteLog");
Object.defineProperty(exports, "createWasteLog", { enumerable: true, get: function () { return createWasteLog_1.createWasteLog; } });
var voidWasteEntry_1 = require("./waste/voidWasteEntry");
Object.defineProperty(exports, "voidWasteEntry", { enumerable: true, get: function () { return voidWasteEntry_1.voidWasteEntry; } });
//# sourceMappingURL=index.js.map