export const routes = {
  login: '/(auth)/login',
  adminRegister: '/(auth)/admin-register',
  staffRegister: '/(auth)/staff-register',
  forgotPassword: '/(auth)/forgot-password',
  pending: '/(auth)/pending',
  rejected: '/(auth)/rejected',
  adminHome: '/(admin)/(tabs)',
  adminStaff: '/(admin)/staff',
  adminAnalytics: '/(admin)/(tabs)/analytics',
  adminCost: '/(admin)/cost',
  adminInventory: '/(admin)/(tabs)/inventory',
  adminWaste: '/(admin)/(tabs)/waste',
  adminAddBatch: '/(admin)/add-batch',
  adminLogWaste: '/(admin)/log-waste',
  staffHome: '/(staff)/(tabs)',
  staffInventory: '/(staff)/(tabs)/inventory',
  staffWaste: '/(staff)/(tabs)/waste',
  staffAddBatch: '/(staff)/add-batch',
  staffLogWaste: '/(staff)/log-waste',
} as const;
